<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="a-0d60a2f203f14" name="com.qtpselenium.suiteA.TestCase_A2" tests="2" failures="0" timestamp="12 Nov 2011 22:19:28 GMT" time="0.000" errors="1">
  <testcase name="testcaseA2" time="0.000" classname="com.qtpselenium.suiteA.TestCase_A2">
    <error type="org.testng.SkipException" message="Runmode for test set data set to no 1">
      <![CDATA[org.testng.SkipException: Runmode for test set data set to no 1
	at com.qtpselenium.suiteA.TestCase_A2.testcaseA2(TestCase_A2.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1031)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1027)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:956)
	at org.testng.TestNG.run(TestNG.java:892)
	at org.testng.TestNG.privateMain(TestNG.java:1174)
	at org.testng.TestNG.main(TestNG.java:1138)
]]>
    </error>
  </testcase>
  <testcase name="testcaseA2" time="0.000" classname="com.qtpselenium.suiteA.TestCase_A2"/>
</testsuite>
